project:
  year: 2018
  owner: Matthew Hartstonge
  custom: <matt@mykro.co.nz>

  licenseType: apache2
  attributionType: short

attributions:
  - name: go
    link: https://github.com/golang/go
    copyright: Copyright (c) 2009 The Go Authors. All rights reserved.
    licenseLink: https://github.com/golang/go/blob/master/LICENSE
    licenseName: BSD 3-clause "New" or "Revised" License
